CREATE DATABASE IF NOT EXISTS users_db;
USE users_db;

CREATE TABLE IF NOT EXISTS users(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100),
    email VARCHAR(120),
    image VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS passwords(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    user_id INT,
    password VARCHAR(70)
);

CREATE TABLE IF NOT EXISTS links(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    user_id INT,
    link VARCHAR(70),
    title VARCHAR(100),
    description TEXT
);